version: '3'
name: algorithm
services:
  algorithm-class:
    build:
      context: .
      args:
        USERNAME: user
    image: tedwang2/algorithm-class:1.0
    container_name: algorithm-class
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    working_dir: /home/user/ALG
    environment:
      - DISPLAY=host.docker.internal:0.0
      - XAUTHORITY=/root/.Xauthority
    volumes:
      # Mount X11 server
      - /d/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Direct Rendering Infrastructure
      - /dev:/dev
      - ../:/home/user/ALG

    command: /bin/bash
